/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktorm.jackson.sample

import org.ktorm.database.Database
import org.ktorm.dsl.from
import org.ktorm.dsl.select
import org.ktorm.jackson.JsonSqlType
import org.ktorm.jackson.sharedObjectMapper
import org.ktorm.schema.Table
import org.ktorm.schema.typeOf

fun main() {
    val database = Database.connect("jdbc:h2:mem:ktorm;INIT=CREATE SCHEMA IF NOT EXISTS TEST\\; CREATE TABLE FOO(BAR VARCHAR(255))\\; INSERT INTO FOO VALUES ('[1,2,3]')")
    for (row in database.from(Foo).select()) {
        println(row[Foo.bar])
    }
}

object Foo : Table<Nothing>("foo") {
    val bar = registerColumn("bar", JsonSqlType(sharedObjectMapper, sharedObjectMapper.constructType(typeOf<List<Int>>())))
}
